### ISSUE TITLE
Stop AutoRotate on hover

### ISSUE THREAD

**Issue by felipeS** [basilio/responsiveCarousel#20]
Is it possible to stop or pause the autoRotation when i am over any item of the carousel ?

Thanks!

**Comment by browniebroke** [comment]
Hum... For some reason I can't get it to work in my case http://jsfiddle.net/brunoalla/46d0zyxp/1/

Am I missing something obvious? The javascript contains https://raw.githubusercontent.com/basilio/responsiveCarousel/master/responsiveCarousel.js followed by the above snippet, from line 413.
