### ISSUE TITLE
Embedded malicious code

### ISSUE THREAD

**Issue by aaron-stripe** [basilio/responsiveCarousel#54]
Hello,

Just wanted to highlight that on July 13, someone committing as @jakob-everson added malicious code to this repo. 

Initial commit is here: https://github.com/basilio/responsiveCarousel/commit/aec0aa71fcdd189e4983c9dedc52e32f2cf4a29f

You can see the malicious code here
: https://github.com/basilio/responsiveCarousel/blob/master/responsiveCarousel.js#L1201

I'm reporting this to cdnjs and GitHub. @basilio - can you clean this up?

**Comment by basilio** [comment]
Thanks @aaron-stripe

**Comment by aaron-stripe** [comment]
Thanks @basilio. Can you explain why @jakob-everson was given access to the repo? And why they are adding malicious code?
